name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main   # change if your default branch is 'master' or else

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.T_GITHUB_TOKEN }}
          publish_dir: ./dist
